# In _config.yml
title: SOLS-processing
author: Sebastian Bundschuh, Johannes Soltwedel, Nazar Oleksiievets
logo: logo.png
execute:
  execute_notebooks: off

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

sphinx:
  extra_extensions:
  - 'sphinx.ext.autodoc'
  - 'sphinx.ext.napoleon'
  - 'sphinx.ext.viewcode'
  - 'sphinx.ext.autosummary'
  config:
    add_module_names: True
    autosummary_generate: True
